version: "4.0"

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  stata_explore:
    run: stata-mp:v2 analysis/explore.do
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        summary: output/processed/stata_summary.csv
        counts: output/processed/stata_counts.csv



